apiVersion: v1
kind: ResourceQuota
metadata:
  name: ministore-quota
  namespace: ministore
spec:
  hard:
    pods: "50"
    requests.cpu: "8"
    requests.memory: 8Gi
    limits.cpu: "16"
    limits.memory: 16Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: container-defaults
  namespace: ministore
spec:
  limits:
    - type: Container
      default: {cpu: 500m, memory: 256Mi}
      defaultRequest: {cpu: 100m, memory: 128Mi}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: ministore
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-traffic
  namespace: ministore
spec:
  podSelector:
    matchLabels: {app.kubernetes.io/name: ministore-api}
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels: {kubernetes.io/metadata.name: ministore}
